/**
 * ARENAKORE — CMS Fallback Content (Offline Safe)
 * Mirror of actual CMS database content for all pages.
 * Used when backend is unreachable — guarantees 100% readable UI.
 *
 * FALLBACK_PAGES[slug][key] → used by usePageContent
 * FALLBACK_GLOBAL[key]      → used by useGlobalContent
 */

export const FALLBACK_PAGES = {

  // ── HOMEPAGE (54 keys) ────────────────────────────────────────────────────
  homepage: {
    seo_title: 'ArenaKore — The Multi-Sport Competition Platform',
    seo_description: 'Every performance is ranked.',
    hero_badge: 'NEXUS LIVE · GLOBAL COMPETITION ACTIVE',
    hero_h1_line1: 'The competition',
    hero_h1_line2: 'never ends.',
    hero_sub: 'Every performance is ranked.',
    hero_scroll: 'Scroll to learn more',
    cta_primary: 'Download the App',
    cta_secondary: 'For Gyms & Coaches',
    stats_active: 'Active KORE',
    stats_rating: 'Max K-Rating',
    stats_validated: 'Rep Validated',
    stats_excuses: 'Excuses Accepted',
    sport_selector_title: "What's your arena?",
    sport_selector_sub: 'Choose your primary discipline',
    problem_badge: 'THE PROBLEM',
    problem_h2: "TRAINING WITHOUT COMPETITION DOESN'T LAST.",
    problem_p1: 'No pressure — missing a session has no consequence.',
    problem_p2: "No accountability — nobody notices if you don't show up.",
    problem_p3: 'No reason to come back — progress feels invisible.',
    insight_line1: "PEOPLE DON'T COME BACK",
    insight_line2: 'TO TRAIN.',
    insight_line3: 'THEY COME BACK',
    insight_line4: 'TO NOT LOSE.',
    insight_body: 'Behavioral science is clear: loss aversion is 2x more motivating than the desire to improve. When performances are ranked, visible and permanent — people show up differently.',
    solution_badge: 'THE SYSTEM',
    solution_h2: 'ARENAKORE TURNS TRAINING INTO COMPETITION.',
    solution_feat1: 'Daily challenges — new challenge every day. Every session has stakes.',
    solution_feat2: 'Live rankings — K-Rating updates in real-time. Public, permanent, undeniable.',
    solution_feat3: "Visible performance — NEXUS validates every rep. You can't fake your score.",
    how_badge: 'HOW IT WORKS',
    how_h2: '4 STEPS. NO EXCUSES.',
    how_s1_title: 'Join a challenge',
    how_s1_desc: 'Pick any discipline, set your target. Challenge open or 1v1.',
    how_s2_title: 'Track your performance',
    how_s2_desc: "NEXUS validates every rep in real-time. Bad form doesn't count.",
    how_s3_title: 'Climb the ranking',
    how_s3_desc: 'K-Rating updates after every session. Public. Permanent.',
    how_s4_title: 'Compete daily',
    how_s4_desc: 'New challenges every day across every discipline.',
    disciplines_badge: 'EVERY ARENA',
    disciplines_h2: 'BUILT FOR EVERY DISCIPLINE.',
    disciplines_sub: 'One ranking system. One identity. Any sport.',
    positioning_badge: 'THE PLATFORM',
    positioning_h2: 'ONE SYSTEM. ANY DISCIPLINE.',
    positioning_body: 'ArenaKore is a competition platform designed for any performance-based activity — from fitness and CrossFit to basketball, running, swimming and beyond.',
    gyms_badge: 'FOR GYM OWNERS',
    gyms_h2: 'BUILT FOR GYMS THAT WANT',
    gyms_engaged: 'ENGAGED MEMBERS.',
    gyms_body: 'The average gym loses 80% of new members within 6 months. ArenaKore gives you a competition layer that makes members come back — because now they have something to lose.',
    gyms_f1: '+40% member retention',
    gyms_f2: 'Live challenge system — no manual setup',
    gyms_f3: 'Box vs box competition across locations',
    gyms_f4: '14-day free pilot. No commitment.',
    gyms_cta: 'Start a 14-day Pilot',
    final_h2: 'START NOW.',
    final_sub: 'Compete or fall behind.',
  },

  // ── FOR ATHLETES ──────────────────────────────────────────────────────────
  'for-athletes': {
    hero_badge: 'FOR ATHLETES',
    hero_h1: "YOU DON'T TRAIN. YOU COMPETE.",
    hero_sub: 'Enter the Arena.',
    hero_cta: 'Start Your First Challenge',
    hero_tagline: 'You are not just training. You are competing.',
    final_cta: 'Enter the Arena',
    identity_pretext: "ONCE YOU ENTER, YOU'RE NOT JUST AN ATHLETE.",
    identity_h2_line1: 'YOU ARE A',
    identity_h2_line2: 'KORE.',
    identity_body: 'A KORE is not a user. Not a member. Not a subscriber. A KORE is a competitor with a permanent record, a certified rank and an identity built entirely on real performance.',
    kore_badge: 'THE KORE SYSTEM',
    kore_h2: 'WHAT IT MEANS TO BE A KORE.',
    kore_challenges: 'CHALLENGES — Daily. Direct. Permanent. Every challenge you accept becomes part of your record.',
    kore_ranking: 'RANKING — K-Rating from 0 to 1000. Earned through performance. Updated after every session.',
    kore_competition: 'COMPETITION — The Arena never closes. There is always someone above you. Always someone targeting your rank.',
    kore_visibility: 'VISIBILITY — Your performance is public. Your history is permanent. You cannot hide your numbers here.',
    kflux_badge: 'K-FLUX',
    kflux_h2: 'EVERY ACTION GENERATES K-FLUX.',
    kflux_body: "K-Flux is the currency of the Arena. It doesn't come from showing up. It comes from performing. From being consistent. From exceeding the rep you were about to skip.",
    kflux_f1: 'Training consistency — Show up 7 days in a row. K-Timeline tracks every session.',
    kflux_f2: 'Validated performance — Every rep certified by NEXUS. Every score earned, not declared.',
    kflux_f3: 'Competitive activity — Accept challenges. Win duels. Enter live events. K-Flux multiplies.',
    kflux_hud_label: 'K-FLUX EARNED TODAY',
    kflux_hud_sub: '3 sessions · 2 challenges · 1 day streak',
    nexus_badge: 'NEXUS ENGINE',
    nexus_h2: 'SCAN. TRACK. EVOLVE.',
    nexus_body: "NEXUS doesn't watch you train. It judges you. Puppet Motion Detection tracks every joint, every angle, every rep. A rep that doesn't meet the standard doesn't count. This is not punishment. It's truth.",
    nexus_f1: 'Biometric tracking — Joint angles, movement timing, range of motion — captured in real time.',
    nexus_f2: 'Performance data — Every session feeds your DNA profile: VEL, FOR, RES, AGI, TEC, POT.',
    nexus_f3: 'Evolution over time — Your DNA score evolves. Not on paper. In data. Visible to all.',
    challenges_badge: 'THE ARENA',
    challenges_h2: 'CHALLENGE ANYONE.',
    final_badge: 'THE FINAL CHOICE',
    final_h2: 'COMPETE OR FALL BEHIND.',
    final_body: "Right now, someone is training harder than you. They're in the Arena. Are you?",
    final_t1: 'Free to start',
    final_t2: 'Reps validated',
    final_t3: 'Rank earned',
  },

  // ── ARENA SYSTEM ──────────────────────────────────────────────────────────
  'arena-system': {
    hero_badge: 'UNIVERSAL COMPETITION SYSTEM',
    hero_h1: 'THE SYSTEM BEHIND THE COMPETITION.',
    hero_sub: 'Track performance. Rank results. Compete every day.',
    hero_sub2: 'Any sport. Any discipline. One system.',
    not_fitness_app: 'This is not a fitness app. This is a competition system.',
    what_badge: 'WHAT IT DOES',
    what_h2: 'THREE THINGS.',
    what_h2_2: 'NO COMPROMISE.',
    track_title: 'Track performance.',
    track_body: 'Every rep, every result — captured and certified. Nothing is lost. Nothing is inflated. Your history is permanent.',
    rank_title: 'Rank every result.',
    rank_body: 'K-Rating from 0 to 1000. Public. Permanent. Updated after every validated competition.',
    challenge_title: 'Create continuous competition.',
    challenge_body: 'New challenges every day. Open or 1v1. Across disciplines. The Arena never closes.',
    why_badge: 'BEHAVIORAL SCIENCE',
    why_h2: 'COMPETITION CHANGES BEHAVIOR.',
    why_1: 'Visibility creates pressure.',
    why_1_body: 'When your score is public, skipping a session has a cost. Visibility is the most powerful behavioral lever in competitive sport.',
    why_2: 'Ranking creates engagement.',
    why_2_body: "Nobody ignores a leaderboard they're on. K-Rating gives every athlete a personal stake in every session.",
    why_3: 'Repetition creates consistency.',
    why_3_body: 'Daily challenges with real consequences build training habits that self-motivation alone cannot sustain.',
    sport_badge: 'ANY DISCIPLINE',
    sport_h2: 'WORKS IN ANY DISCIPLINE.',
    sport_body: "ArenaKore is not built for one sport. It's built for any activity where performance can be measured, validated and compared.",
    nexus_badge: 'POWERED BY NEXUS',
    nexus_callout: 'NEXUS VALIDATES EVERY REP.',
    nexus_body: "Puppet Motion Detection. Real-time bio-analysis. Bad form doesn't count.",
    final_h2: 'ENTER THE SYSTEM.',
    final_body: 'ArenaKore is a universal competition system for any performance-based activity.',
  },

  // ── GET THE APP ───────────────────────────────────────────────────────────
  'get-the-app': {
    hero_badge: 'FREE DOWNLOAD',
    hero_h1: 'ENTER THE ARENA.',
    hero_tension: 'Someone is already ahead.',
    hero_sub1: 'Track your performance.',
    hero_sub2: 'Get ranked. Compete.',
    available: 'Available now',
    download_time: 'Download in 10 seconds',
    free_note: 'Free · No credit card · Available worldwide',
    what_badge: 'WHAT YOU GET',
    what_h2: 'THREE THINGS. ZERO EXCUSES.',
    what_h2_2: 'ZERO EXCUSES.',
    track_badge: '01 / TRACK',
    track_headline: 'Every performance is recorded.',
    track_body: 'NEXUS validates every rep, every result. Nothing is lost. Nothing is inflated. Your history is permanent.',
    rank_badge: '02 / RANK',
    rank_headline: 'You are not training. You are competing.',
    rank_body: 'K-Rating from 0 to 1000. Updated after every session. Compared globally. You always know where you stand.',
    challenge_badge: '03 / CHALLENGE',
    challenge_headline: 'Launch or accept challenges anytime.',
    challenge_body: 'Direct 1v1. Open events. Live competitions. The Arena is always open. There is always someone to beat.',
    next_badge: 'THE PROCESS',
    next_title: 'What happens next',
    next_1: 'You perform',
    next_2: 'You get ranked',
    next_3: 'You get compared',
    next_4: 'You come back',
    sport_badge: 'YOUR ARENA',
    sport_h2: 'Your sport.',
    sport_h2_line1: 'Your sport.',
    sport_h2_line2: 'Your arena.',
    sport_body: 'ArenaKore works across any discipline. One identity. One ranking. Any sport.',
    proof_badge: 'LIVE NOW',
    proof_perf: '1,024 performances tracked today',
    proof_athletes: '28 athletes competing now',
    final_h2_line1: 'DOWNLOAD.',
    final_h2_line2: 'ENTER.',
    final_h2_line3: 'COMPETE.',
    final_body: 'The Arena is open. Your rank is waiting. Every day you delay is a day someone else advances.',
    final_free: 'Free to download · Available worldwide',
    final_learn: 'Learn about the Arena System',
  },

};

// ─── GLOBAL CONTENT ──────────────────────────────────────────────────────────
// Keys used by useGlobalContent (navbar, footer)

export const FALLBACK_GLOBAL = {
  // Navbar
  nav_home:         'Home',
  nav_arena_system: 'Arena System',
  nav_athletes:     'Athletes',
  nav_competition:  'Competition',
  nav_amrap:        'AMRAP',
  nav_crossfit:     'CrossFit',
  nav_business:     'Business',
  nav_blog:         'Blog',
  nav_cta:          'Start Your Challenge',

  // Footer
  footer_tagline:   'Global competition platform for athletes and gyms.',
  footer_nexus:     'NEXUS ONLINE',
  footer_copyright: '© 2026 ArenaKore. All rights reserved.',
};
